name: Vulnerability Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Image
        run: docker build -t app .
      - name: Scan the Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image: app
      - name: Scan the Docker Image
        run: |
            trivy image --format table --severity HIGH,CRITICAL my-image
